import "server-only";
import { createClient } from "@/lib/supabase/server";
import { getCurrentBrand } from "@/lib/data/brand";
import type { BrandSummary } from "@/lib/data/brand";

// Brand Chat data layer (Screen 19, /chat).
// Source: chat_conversations + chat_messages, both RLS-scoped to the brand
// (chat_conversations: brand_id IN get_user_brand_ids(); chat_messages: joined
// through its conversation). This module is read-only — it lists the brand's
// real conversations and a conversation's real message history.
//
// The assistant reply itself is generated by a Supabase Edge Function (GPT-4.1
// Mini, brand context injected) that is NOT deployed yet (Sprint 3, blocked on
// API keys). So `inline_data`/assistant rows only exist once that pipeline runs;
// until then the UI honestly shows a "assistant activates when your pipeline is
// live" notice and never fabricates an answer.

export type { BrandSummary };

/** Shape of the `inline_data` JSONB column on an assistant message
 *  (Sprint-3 WRITE TARGET — the Edge Function emits structured data tables the
 *  thread renders inline). Parsed defensively; never trusted by shape. */
export type ChatInlineData = {
  table?: { columns: string[]; rows: string[][] };
};

/** One conversation in the left-hand list. */
export type ChatConversation = {
  id: string;
  title: string;
  messageCount: number;
  lastMessageAt: string | null;
  createdAt: string | null;
  profileId: string;
};

export type ChatMessageRole = "user" | "assistant" | "system";

/** One message in the thread. */
export type ChatMessage = {
  id: string;
  role: ChatMessageRole;
  content: string;
  inlineData: ChatInlineData | null;
  modelUsed: string | null;
  createdAt: string | null;
};

const isRecord = (v: unknown): v is Record<string, unknown> =>
  typeof v === "object" && v !== null && !Array.isArray(v);

/** Parse `inline_data` defensively — only surface a well-formed table. */
function parseInlineData(raw: unknown): ChatInlineData | null {
  if (!isRecord(raw)) return null;

  const table = raw.table;
  if (!isRecord(table)) return null;

  const columns = Array.isArray(table.columns)
    ? table.columns.filter((c): c is string => typeof c === "string")
    : [];

  const rows = Array.isArray(table.rows)
    ? table.rows
        .filter((row): row is unknown[] => Array.isArray(row))
        .map((row) => row.map((cell) => (cell == null ? "" : String(cell))))
    : [];

  if (columns.length === 0 && rows.length === 0) return null;

  return { table: { columns, rows } };
}

function normaliseRole(raw: string): ChatMessageRole {
  return raw === "assistant" || raw === "system" ? raw : "user";
}

/** The brand's conversations, most-recently-active first.
 *  Orders by last_message_at desc with nulls last (a freshly created
 *  conversation with no assistant reply yet still sorts sensibly).
 *  Returns an empty list (not null) when none exist — the page renders the
 *  SuggestedPrompts starter surface from a clean []. */
export async function getConversations(
  brand: BrandSummary,
): Promise<ChatConversation[]> {
  const supabase = createClient();
  const { data: rows } = await supabase
    .from("chat_conversations")
    .select("id, title, message_count, last_message_at, created_at, profile_id")
    .eq("brand_id", brand.id)
    .order("last_message_at", { ascending: false, nullsFirst: false })
    .order("created_at", { ascending: false, nullsFirst: false });

  if (!rows || rows.length === 0) return [];

  return rows.map((r): ChatConversation => ({
    id: r.id,
    title: r.title?.trim() || "New chat",
    messageCount: r.message_count ?? 0,
    lastMessageAt: r.last_message_at,
    createdAt: r.created_at,
    profileId: r.profile_id,
  }));
}

/** A conversation's messages, oldest first (thread order).
 *  RLS scopes the read to the brand via the conversation join, so an unknown or
 *  cross-brand conversationId simply yields []. */
export async function getMessages(
  conversationId: string,
): Promise<ChatMessage[]> {
  const supabase = createClient();
  const { data: rows } = await supabase
    .from("chat_messages")
    .select("id, role, content, inline_data, model_used, created_at")
    .eq("conversation_id", conversationId)
    .order("created_at", { ascending: true });

  if (!rows || rows.length === 0) return [];

  return rows.map((r): ChatMessage => ({
    id: r.id,
    role: normaliseRole(r.role),
    content: r.content,
    inlineData: parseInlineData(r.inline_data),
    modelUsed: r.model_used,
    createdAt: r.created_at,
  }));
}

/** Re-exported for page convenience. */
export { getCurrentBrand };
