-- Section 4: Intelligence cache tables

CREATE TABLE weekly_cache (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  brand_id uuid NOT NULL REFERENCES brands(id) ON DELETE CASCADE,
  scan_week date NOT NULL,
  scan_job_id uuid REFERENCES scan_jobs(id),
  reach_score numeric(5,2),
  aggression_score numeric(5,2),
  threat_score numeric(5,2),
  sov_pct numeric(5,2),
  threat_level text CHECK (threat_level IN ('low','medium','high','critical')),
  threat_reasons text[],
  ai_visibility_score numeric(5,2),
  ai_visibility_trend numeric(5,2),
  competitors_tracked integer,
  promo_changes_this_week integer,
  active_ads_count integer,
  promotions_data jsonb,
  traffic_seo_data jsonb,
  social_data jsonb,
  ads_data jsonb,
  tech_stack_data jsonb,
  product_data jsonb,
  customer_data jsonb,
  regulatory_data jsonb,
  hiring_data jsonb,
  geo_aeo_data jsonb,
  radar_data jsonb,
  competitor_states jsonb,
  cached_at timestamptz DEFAULT now(),
  expires_at timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(brand_id, scan_week)
);

CREATE TABLE promotions_cache (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  brand_id uuid NOT NULL REFERENCES brands(id) ON DELETE CASCADE,
  scan_week date NOT NULL,
  competitor_id uuid NOT NULL REFERENCES competitors(id),
  bonus_amount_kobo bigint,
  wagering_requirement numeric(5,2),
  promo_type text,
  promo_title text,
  promo_url text,
  is_new boolean DEFAULT false,
  wow_bonus_change_pct numeric(5,2),
  wow_wagering_change_pct numeric(5,2),
  raw_data jsonb,
  source_url text,
  scraped_at timestamptz,
  evidence_hash text,
  created_at timestamptz DEFAULT now(),
  UNIQUE(brand_id, scan_week, competitor_id)
);

CREATE TABLE seo_cache (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  brand_id uuid NOT NULL REFERENCES brands(id) ON DELETE CASCADE,
  scan_week date NOT NULL,
  competitor_id uuid NOT NULL REFERENCES competitors(id),
  estimated_traffic bigint,
  organic_traffic bigint,
  paid_traffic bigint,
  domain_authority numeric(5,2),
  keyword_gaps jsonb,
  serp_positions jsonb,
  content_gaps jsonb,
  google_ads_data jsonb,
  raw_data jsonb,
  created_at timestamptz DEFAULT now(),
  UNIQUE(brand_id, scan_week, competitor_id)
);

CREATE TABLE geo_cache (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  brand_id uuid NOT NULL REFERENCES brands(id) ON DELETE CASCADE,
  scan_week date NOT NULL,
  ai_visibility_score numeric(5,2),
  score_change_wow numeric(5,2),
  chatgpt_mentioned boolean,
  chatgpt_sentiment text CHECK (chatgpt_sentiment IN ('positive','neutral','negative')),
  chatgpt_position integer,
  chatgpt_response_sample text,
  chatgpt_checked_at timestamptz,
  claude_mentioned boolean,
  claude_sentiment text CHECK (claude_sentiment IN ('positive','neutral','negative')),
  claude_position integer,
  claude_response_sample text,
  claude_checked_at timestamptz,
  gemini_mentioned boolean,
  gemini_sentiment text CHECK (gemini_sentiment IN ('positive','neutral','negative')),
  gemini_position integer,
  gemini_response_sample text,
  gemini_checked_at timestamptz,
  perplexity_mentioned boolean,
  perplexity_sentiment text CHECK (perplexity_sentiment IN ('positive','neutral','negative')),
  perplexity_position integer,
  perplexity_response_sample text,
  perplexity_checked_at timestamptz,
  grok_mentioned boolean,
  grok_sentiment text CHECK (grok_sentiment IN ('positive','neutral','negative')),
  grok_position integer,
  grok_checked_at timestamptz,
  top_ai_mentions jsonb,
  competitor_ai_scores jsonb,
  featured_snippets jsonb,
  paa_appearances jsonb,
  raw_data jsonb,
  created_at timestamptz DEFAULT now(),
  UNIQUE(brand_id, scan_week)
);

CREATE TABLE social_cache (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  brand_id uuid NOT NULL REFERENCES brands(id) ON DELETE CASCADE,
  scan_week date NOT NULL,
  competitor_id uuid NOT NULL REFERENCES competitors(id),
  facebook_followers bigint,
  instagram_followers bigint,
  tiktok_followers bigint,
  twitter_followers bigint,
  youtube_followers bigint,
  weekly_posts integer,
  avg_engagement_rate numeric(5,2),
  dominant_content_theme text,
  active_ads_count integer,
  ads_data jsonb,
  raw_data jsonb,
  scraped_at timestamptz,
  created_at timestamptz DEFAULT now(),
  UNIQUE(brand_id, scan_week, competitor_id)
);

CREATE TABLE tech_stack_cache (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  competitor_id uuid NOT NULL REFERENCES competitors(id) ON DELETE CASCADE,
  scan_week date NOT NULL,
  technologies jsonb NOT NULL DEFAULT '[]',
  ad_networks text[] DEFAULT '{}',
  crm_tools text[] DEFAULT '{}',
  analytics_tools text[] DEFAULT '{}',
  payment_gateways text[] DEFAULT '{}',
  cdn_providers text[] DEFAULT '{}',
  changes_detected jsonb DEFAULT '[]',
  raw_response jsonb,
  scanned_at timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now(),
  UNIQUE(competitor_id, scan_week)
);

CREATE TABLE hiring_signals_cache (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  brand_id uuid NOT NULL REFERENCES brands(id) ON DELETE CASCADE,
  scan_week date NOT NULL,
  competitor_id uuid NOT NULL REFERENCES competitors(id),
  roles jsonb DEFAULT '[]',
  signal_types text[] DEFAULT '{}',
  interpreted_signals jsonb DEFAULT '[]',
  geographic_expansion jsonb,
  raw_data jsonb,
  created_at timestamptz DEFAULT now(),
  UNIQUE(brand_id, scan_week, competitor_id)
);

CREATE TABLE product_intel_cache (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  brand_id uuid NOT NULL REFERENCES brands(id) ON DELETE CASCADE,
  scan_week date NOT NULL,
  competitor_id uuid NOT NULL REFERENCES competitors(id),
  sports_betting_status text CHECK (sports_betting_status IN ('active','growing','declining','absent')),
  crash_games_status text CHECK (crash_games_status IN ('active','growing','declining','absent')),
  casino_status text CHECK (casino_status IN ('active','growing','declining','absent')),
  lottery_status text CHECK (lottery_status IN ('active','growing','declining','absent')),
  aviator_promo_active boolean DEFAULT false,
  aviator_bonus_structure jsonb,
  new_products_detected text[] DEFAULT '{}',
  odds_competitiveness_score numeric(5,2),
  raw_data jsonb,
  created_at timestamptz DEFAULT now(),
  UNIQUE(brand_id, scan_week, competitor_id)
);

CREATE TABLE customer_intel_cache (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  brand_id uuid NOT NULL REFERENCES brands(id) ON DELETE CASCADE,
  scan_week date NOT NULL,
  competitor_id uuid NOT NULL REFERENCES competitors(id),
  traffic_sources jsonb,
  demographics jsonb,
  geographic_distribution jsonb,
  complaint_themes jsonb,
  app_rating numeric(3,2),
  app_review_count integer,
  sentiment_score numeric(3,2),
  raw_data jsonb,
  created_at timestamptz DEFAULT now(),
  UNIQUE(brand_id, scan_week, competitor_id)
);

CREATE TABLE regulatory_cache (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  brand_id uuid NOT NULL REFERENCES brands(id) ON DELETE CASCADE,
  scan_week date NOT NULL,
  competitor_id uuid NOT NULL REFERENCES competitors(id),
  market text NOT NULL,
  licence_display_status text CHECK (licence_display_status IN ('compliant','partial','non_compliant')),
  responsible_gambling_status text CHECK (responsible_gambling_status IN ('compliant','partial','non_compliant')),
  bonus_terms_status text CHECK (bonus_terms_status IN ('compliant','partial','non_compliant')),
  age_verification_status text CHECK (age_verification_status IN ('compliant','partial','non_compliant')),
  withdrawal_terms_status text CHECK (withdrawal_terms_status IN ('compliant','partial','non_compliant')),
  data_privacy_status text CHECK (data_privacy_status IN ('compliant','partial','non_compliant')),
  compliance_score numeric(5,2),
  violations jsonb DEFAULT '[]',
  raw_data jsonb,
  created_at timestamptz DEFAULT now(),
  UNIQUE(brand_id, scan_week, competitor_id, market)
);
